### ISSUE TITLE
laravel migrations - Add column default value

### ISSUE THREAD

**Issue by ericlbarnes** [UserScape/Laravel-Bundles#12]
I am adding a new migration and would like to be able to add a default value. 

``` php
Schema::table('bundles', function($table)
{
    $table->string('active', 1);
    $table->key('index', 'status');
});
```

It would be nice in situations like this where I could define a default value so all existing records are updated. Example: 

``` php
Schema::table('bundles', function($table)
{
    $table->string('active', 1, 'y');
    $table->key('index', 'status');
});
```

**Comment by taylorotwell** [comment]
$table->string('active', 1)->default('Y');
