### ISSUE TITLE
PHP Tags in Description

### ISSUE THREAD

**Issue by daylerees** [UserScape/Laravel-Bundles#33]
It would be handy to be able to post PHP tags in the description when submitting a bundle.

For example :

```
<?php Anbu::render(); ?>
```

Just kills the description field, or acts in an odd way! 

Cheers!

**Comment by taylorotwell** [comment]
It's markdown so should be able to just tab that line to make it render as code...

**Comment by daylerees** [comment]
That's what I thought but it removed the line. I added <?php echo "test"; ?> to the top and that killed it completely.

**Comment by daylerees** [comment]
Hello @taylorotwell I'm still looking for help on this issue from 2012 😃

**Comment by ericlbarnes** [comment]
Unacceptable. This should be reopened immediately and a formal apology given.

**Comment by ericlbarnes** [comment]
Oh wait you still need help on this. 😀 I apologize for my earlier comment.  I’m sure we can use a npm package for this solution.

**Comment by daylerees** [comment]
Haha :)
