### ISSUE TITLE
Bundle dependencies shown as NULL

### ISSUE THREAD

**Issue by daylerees** [UserScape/Laravel-Bundles#34]
I posted initially in the wrong repo, best to look here to see the problem :

https://github.com/laravel/laravel/issues/384

Thanks!

**Comment by colbyr** [comment]
Like Dayle said, I have Eloquent listed as a dependency.

![Dependencies](http://f.cl.ly/items/0k1w2n2k092P2z3F1D1j/dependecy%20error.png)

 it shows up as [null] in the api response:

```
{"status":"ok","bundle":{"name":"aware","provider":"github","location":"crabideau5691\/aware","path":"aware","dependencies":[null]}}
```

I tried deleting the dependency, but the changes don't seem to save properly.

cheers!
