### ISSUE TITLE
Remove Eloquent from featured

### ISSUE THREAD

**Issue by ericlbarnes** [UserScape/Laravel-Bundles#39]
Need to decide on a new bundle to feature. Maybe we can just get a list of 5 or so and rotate randomly.

**Comment by paulboco** [comment]
Perhaps a list of 5 with priority towards new and updated bundles.

**Comment by ericlbarnes** [comment]
@paulboco I changed that query around so it now those 5 sort by most ratings. Probably should still get more info like installs and weight those.

**Comment by taylorotwell** [comment]
Hmm, yeah. What are the most popular?

**Comment by ericlbarnes** [comment]
Most installs: 
http://o7.no/H5c0WB

Most rated:
http://o7.no/Hucck0

**Comment by taylorotwell** [comment]
What about "Bob"? Pretty interesting bundle that can generate stuff for you. I haven't played with it myself. Ill install it tonight and take it for a spin.

**Comment by paulboco** [comment]
Perhaps tabs that order by 'Most Popular', 'New', 'Top Rated', etc ...
As an aside, I would like to see the last updated date (maybe even Laravel version) of bundles I follow.

**Comment by paulboco** [comment]
With a name like "What about Bob?", I must try it too. ;)

**Comment by paulboco** [comment]
Eric, looks good! Just curious, do new bundles rise to the top?

**Comment by ericlbarnes** [comment]
@paulboco The 5 newest or updated bundles always appear on the right side of the home page. The left side is/will be filtered by number of ratings. Unless that changes. 

@taylorotwell bob sounds good and will make @daylerees happy.

**Comment by paulboco** [comment]
@ericbarnes Perfect! Could there be a 'NEW' tag?

**Comment by ericlbarnes** [comment]
Actually we had a new and updated tag. Don't know what happened to those guys. But yeah should be able to add it back.

**Comment by paulboco** [comment]
Just a 'NEW' tag would suffice for me.
After just realizing that your question was about most featured (duh), I would go with random offerings. That would be most fair to the author.

**Comment by daylerees** [comment]
Bob will thank you, but now you force me to update the Model generation, at the moment its still Eloquent\Model, will fix it soon!

@paulboco you can take a peek at bob here http://daylerees.github.com/laravel-bob/

**Comment by ericlbarnes** [comment]
@daylerees Can you get me a short description of bob for the bundle home page? and an image the same size as the current eloquent one?

**Comment by taylorotwell** [comment]
@daylerees the image needs to be something besides the yao ming meme too… ;)

**Comment by ericlbarnes** [comment]
@taylorotwell lol :)

**Comment by daylerees** [comment]
@taylorotwell mate, do I diss your logo? :p haha

Sure no probs, I will have something by tonight.

**Comment by ericlbarnes** [comment]
> Bob builds all kinds of resources for your project from the artisan command line interface. Generate controllers, views, models, tasks, tests and more!
